-- Run this in Supabase SQL editor.
-- Creates the media_items table + RLS policies.

create table if not exists public.media_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,

  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie','tv')),

  -- scope lets you store: whole title/movie, a season, or a single episode
  scope text not null check (scope in ('title','season','episode')),
  season_number integer,
  episode_number integer,

  title text not null,
  year text,
  poster_url text,
  backdrop_url text,

  format text default 'Digital',
  rating numeric,
  comment text,

  genre text,
  cast text,
  overview text,
  runtime text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- prevent duplicates for the same user + same thing
  unique (user_id, tmdb_id, media_type, scope, season_number, episode_number)
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_media_items_updated_at on public.media_items;
create trigger trg_media_items_updated_at
before update on public.media_items
for each row execute function public.set_updated_at();

alter table public.media_items enable row level security;

drop policy if exists "read own items" on public.media_items;
create policy "read own items"
on public.media_items for select
using (auth.uid() = user_id);

drop policy if exists "insert own items" on public.media_items;
create policy "insert own items"
on public.media_items for insert
with check (auth.uid() = user_id);

drop policy if exists "update own items" on public.media_items;
create policy "update own items"
on public.media_items for update
using (auth.uid() = user_id);

drop policy if exists "delete own items" on public.media_items;
create policy "delete own items"
on public.media_items for delete
using (auth.uid() = user_id);
